config/routes.rb
Rails.application.routes.draw do

  resources :recipes
  root to: 'items#index'


  resources :items, except: [:create, :delete, :update] do
    get 'item_auctions_data'
  end
  resources :auctions, except: [:create, :delete, :update]

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :item
  has_many :ingredients
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  def index
    @t_id = Timestamp.order(:created_at).last.id
    @recipes = recipes
  end

  # GET /recipes/1
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params)
    asd = params
    if @recipe.save
      params['recipe']['ingredients'].each do |id|
        next if id.blank?
        @recipe.ingredients.push(Ingredient.new(item_id: id))
      end
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /recipes/1
  def update
    @ingredient = Ingredient.find(ingredient_params['id']) rescue nil
    @recipe = Recipe.find(recipe_params['id']) rescue nil
    puts params
    render json: {status: 'error'} and return if @ingredient.nil? && @recipe.nil?

    @ingredient.update(ingredient_params) if !@ingredient.nil?
    @recipe.update(recipe_params) if !@recipe.nil?

    render json: {status: 'success'}
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private
    def recipes
      page_param = set_pagination_param
      recipe = params[:recipe]

      if recipe
        query = Recipe.where("name ~* ?", recipe[:name].strip)
      else
        query = Recipe.where.not(name: '')
      end

      query#.page(page_param).per(32)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def recipe_params
      params.require(:recipe).permit(:id, :name, :item_id, :tag)
    end

    def ingredient_params
      params.require(:ingredient).permit(:count, :id)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= bootstrap_form_for(Recipe.new, url: recipes_path, method: :create, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-4") do |f|%>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= f.text_field :name, hide_label: true, placeholder: 'Recipe name...', value: @last_search %>
  <br>
  <%= f.select :item_id, Item.where(itemLevel: (100..1000)).map{|q| [q.name, q.id]}, {label: 'Product:'}, {class: 'chosen-select'} %>
  <br>
  <%= f.select :ingredients, Item.where(itemLevel: (100..1000)).map{|q| [q.name, q.id]}, {label: 'Ingredients:'}, {multiple: true, class: 'chosen-select'} %>


  <%= f.submit 'Create', class: 'btn btn-primary' %>
<% end %>

<script type="text/javascript">
  
  $('.chosen-select').chosen()
</script>

app/views/recipes/_recipe_items.html.erb
<table class='ingredients-table-<%= recipe.id %>'>
  <% ingredients.each do |i| %>
  <tr class='prices'>
    <td style='padding: 1px 5px; width: 210px;''>
      <img src="https://wow.zamimg.com/images/wow/icons/small/<%= i.item.icon %>.jpg"> 
      <%= link_to i.item.name, i.item %> 
    <td style='padding: 1px 2px; text-align: right; width: 45px;' class='price'>
      <span class='price-gold-pending-<%=i.item.id%> money-gold'><i class="fa fa-spinner fa-spin"></i></span>
    <td style='padding: 1px 1px; text-align: right; width: 25px;' class='price'>
      <span class='price-silver-pending-<%=i.item.id%> money-silver'></span>
    <td style='padding: 1px 5px; width: 5px;'>x
    <td style='padding: 1px 1px; text-align: right; width: 10px;' class='count'>
      <%= i.count %>
    <td style='padding: 1px 5px; text-align: right'>
      =

    <td style='padding: 1px 2px; text-align: right; width: 45px;' class='price-mul'>
      <span class='money-gold'><i class="fa fa-spinner fa-spin"></i></span>
    <td style='padding: 1px 1px; text-align: right; width: 25px;' class='price-mul'>
      <span class='money-silver'><i class="fa fa-spinner fa-spin"></i></span>

  <% end %>

  <tr class='sum'>
    <td style='padding: 1px 5px;''>
    <td colspan=5>

    <td style='padding: 1px 2px; text-align: right; border-top: 1px black dotted;'>
      <span id='price-gold' class='money-gold'><i class="fa fa-spinner fa-spin"></i></span>
    <td style='padding: 1px 1px; text-align: right; border-top: 1px black dotted;'>
      <span id='price-silver' class='money-silver'></span>

  <tr class='item'>
    <td style='padding: 1px 5px; width: 210px;''>
      <img src="https://wow.zamimg.com/images/wow/icons/small/<%= item.icon %>.jpg"> 
      <%= link_to item.name, item %> 
    <td colspan=4>
    <td> - 
    <td style='padding: 1px 2px; text-align: right; width: 45px;'>
      <span class='price-gold-pending-<%=item.id%> money-gold'><i class="fa fa-spinner fa-spin"></i></span>
    <td style='padding: 1px 1px; text-align: right; width: 25px;'>
      <span class='price-silver-pending-<%=item.id%> money-silver'></span>

  <tr class='result'>
    <td colspan=6>

    <td style='padding: 1px 2px; text-align: right; width: 45px; border-top: 1px black dotted;'>
      <span class='money-gold' style='font-weight: bold;'>-</span>
    <td style='padding: 1px 1px; text-align: right; width: 25px; border-top: 1px black dotted;'>
      <span class='money-silver' style='font-weight: bold;'></span>

</table>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= bootstrap_form_for(@recipe, url: recipe_path, method: :put, 
  layout: :inline, remote: true) do |f|%>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= f.hidden_field :id, value: @recipe.id.to_s %>
  <%= f.text_field :name, placeholder: 'Recipe name...' %>
  <%= f.text_field :tag, placeholder: 'Tag..' %>
  <span class='submit_status'></span>
  <%= f.submit 'Create', class: 'btn btn-primary', style: 'display: none;' %>
<% end %>
<br>


<%= @recipe.ingredients.each do |i| %>
  <%= bootstrap_form_for(i, url: recipe_path, method: :put, 
    layout: :inline, remote: true) do |f|%>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= f.hidden_field :id, value: i.id.to_s %>
  <%= f.text_field :count, label: i.item.name, placeholder: 'count' %>

  <%= f.submit 'Save', class: 'btn btn-primary', style: 'display: none;' %>
  <span class='submit_status'></span>
  <div class='label_status'></div>
<% end %>




<% end %>

<script type="text/javascript">
  
function submitForm(form){
  form.find('input[type=submit]').trigger('click')
  setTooltipStatus(form)
}

function setTooltipStatus(form){
  var span  = form.find('span.submit_status')
  span.html('<i class="fa fa-check fa-fw"></i> Zapisano zmiany')
}

function setSpinnerStatus(form){
  var span = form.find('span.submit_status')
  span.html('<i class="fa fa-circle-o-notch fa-spin fa-fw"></i> Zapisywanie zmian')
}
var delay = (function(){
  var timer = 0;
  return function(callback, ms){
    clearTimeout (timer);
    timer = setTimeout(callback, ms);
  };
})();

var form = $('.form-inline')
console.log('action: ' + form.attr('action'))

form.find('input').on('keyup', function(d){
  setSpinnerStatus  ($(d.target).parents('form'))
  delay(function(){
    console.log($(d.target).val())
    submitForm($(d.target).parents('form'))
    setTooltipStatus($(d.target).parents('form'))
  }, 350 );
})

</script>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<style>
.money-gold::after {
    content: "g";
    color: #DDB100;
}
.money-silver::after {
    content: "s";
    color: #bbb;
}

</style>

<%= link_to 'New Recipe', new_recipe_path, class: 'btn btn-primary' %>

<% if @recipes %>
  <% @recipes.distinct.order(:tag).pluck(:tag).each do |tag| %>
    <h2> <%= tag %> </h2>
    <div class='row'>
      <% @recipes.where(tag: tag).each do |recipe| %>
        <div class='col-md-3' style="background-color: #ddd; border-radius: 5px; width: 400px; margin: 5px;">
          <h3>
            <%= link_to recipe.name, edit_recipe_path(recipe) %>
            (<%= recipe.id %>)
            <%#= link_to 'X', recipe_path(recipe), method: :delete, 
              class: 'btn btn-danger btn-xs', 
              data: { confirm: "Are you sure?" } %>
          </h3>
          <%= render 'recipe_items', ingredients: recipe.ingredients, recipe: recipe, item: recipe.item %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>
<br>

<script>

  $.each(<%=@recipes.map{|q| [q.item.id] + q.ingredients.map{|q| q.item.id}}.flatten.uniq %>, function(_, id){
    get_item_data(id);
  })

  function get_item_data(item_id){
    $.ajax({
      url         : 'items/' + item_id + '/item_auctions_data?timestamp_id=' + '<%=@t_id%>',
      type        : "get", //typ połączenia
      contentType : 'application/json', //gdy wysyłamy dane czasami chcemy ustawić ich typ
      dataType    : 'json', //typ danych jakich oczekujemy w odpowiedzi
    }).done(function(response) {
      $('.auctions-pending-' + item_id).text(response.auctions)
      $('.price-gold-pending-' + item_id).text(response.lowest_price.gold)
      $('.price-silver-pending-' + item_id).text(response.lowest_price.silver)
      $('.updated-at-pending-' + item_id).text(response.updated_at)
      count_prices()
    })
  }

  function count_prices(){
    for ( id of <%= @recipes.map{|q| q.id} %> ){
      sumg = 0
      sums = 0
      g = 0
      s = 0
      mul = 0
      s_g = 0
      $('.ingredients-table-' + id).each(function(i){
        $(this).find('tr').each(function(tr){
          g = $(this).find('td.price span.money-gold').text()
          s = $(this).find('td.price span.money-silver').text()
          mul = $(this).find('td.count').text()
          console.log(g)
          smul = parseInt(s) * parseInt(mul)
          s_g = parseInt(smul / 100)
          $(this).find('td.price-mul span.money-silver').text(parseInt(s) * parseInt(mul) - s_g*100)
          $(this).find('td.price-mul span.money-gold').text(parseInt(g) * parseInt(mul) + s_g)
        })
        $(this).find('tr.prices td.price-mul span.money-gold').each(function(gold){
          g = $(this).text()
          sumg += parseInt(g)
        })
        $(this).find('tr.prices td.price-mul span.money-silver').each(function(gold){
          s = $(this).text()
          sums += parseInt(s)
        })
        $(this).find('tr.sum td span.money-gold').each(function(gold){
          s_g = parseInt(sums / 100)
          sumg = sumg + s_g
          $(this).text(sumg)
        })
        $(this).find('tr.sum td span.money-silver').each(function(gold){
          sums = sums - s_g*100
          $(this).text(sums)
        })

        itemg = $(this).find('tr.item td span.money-gold').text()
        items = $(this).find('tr.item td span.money-silver').text()
        if (parseInt(itemg) - sumg <= 0){
          s_g = 
          $(this).find('tr.result td span.money-gold').text(parseInt(itemg) - sumg).css('color', 'red')
          $(this).find('tr.result td span.money-silver').text(Math.abs(parseInt(items) - sums)).css('color', 'red')
          $(this).parent('div').css('background-color', '#fbb')
        }
        else {
          $(this).find('tr.result td span.money-gold').text(parseInt(itemg) - sumg).css('color', 'green')
          $(this).find('tr.result td span.money-silver').text(Math.abs(parseInt(items) - sums)).css('color', 'green')
          $(this).parent('div').css('background-color', '#bfb')


        }
      })
    }
  }
</script>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>