config/routes.rb
Rails.application.routes.draw do

  resources :recipes
  root to: 'items#index'


  resources :items, except: [:create, :delete, :update] do
    get 'item_auctions_data'
  end
  resources :auctions, except: [:create, :delete, :update]

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/auction.rb
class Auction < ApplicationRecord
  # validates :auc, uniqueness: true

  # validates :bid, exclusion: { in: %w(0) }
  # validates :buyout, exclusion: { in: %w(0) }
  # validates :quanity, exclusion: { in: %w(0) }
  belongs_to :timestamp

  def without_item
    json = {}
    VALID_AUCTION_FIELDS.each{|vk| json[vk.to_sym] = self[vk]}
    json[:buyout_per_unit] = json[:buyout].to_f / json[:quantity].to_f
    json
  end

  def self.get_auctions_api
    json_response = JSON.parse(open(AUCTIONS_API_SRC + API_KEY_WITH_LOCALE).read)
  end

  def self.get_auctions
    require 'open-uri'
    auctions_api = self.get_auctions_api
    timestamp = auctions_api['files'].first['lastModified'].to_f/1000
    auction_house_data_src = auctions_api['files'].first['url']
    json_response = JSON.parse(open(auction_house_data_src).read)

    item_ids = Item.where(itemLevel: (100..5000)).pluck(:item_id)
    self.add_records(json_response['auctions'].select{|i| item_ids.include?(i['item'])}, timestamp)
  end

  def self.actualize_items
    require 'sidekiq'
    Auction.all.each_with_index do |a, i|
      ItemWorker.perform_async(a.item)
    end
  end

  private

  def self.add_records(auctions, t)
    last_timestamp = Timestamp.where(timestamp: t).first
    if last_timestamp
      return nil
    else
      ts = Timestamp.new(timestamp: t)
      ts.save
      ts_id = ts.id
    end
    puts "Found #{auctions.count} auctions..."
    auctions.each do |auction_json|
      AuctionWorker.perform_async(auction_json, ts_id)
    end
  end

  # auction timeLeft:
  #
  # very long: 12  - 48h
  # long:      2   - 12h
  # medium:    0.5 - 2h
  # short:     0   - 0.5h

end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, only: [:show, :edit, :update, :destroy]

  # GET /auctions
  # GET /auctions.json
  def index
    @auctions = auctions
    @last_search = params[:auction][:owner] rescue ''
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
  end

  private

    def auctions
      page_param = set_pagination_param
      auction = params[:auction]

      if auction
        query = Auction.where("owner ~* ?", auction[:owner].strip)
        query2 = query.where(timestamp: Timestamp.order(:created_at).last)
        if query2.count == 0 && Timestamp.count > 1
          query2 = query.where(timestamp: Timestamp.order(:created_at).all[-2])
        end
        query = query2
      else
        query = Auction.all
      end

      query.page(page_param).per(64)
    end
    # Use callbacks to share common setup or constraints between actions.

    def set_pagination_param
      unless params[:page].blank?
        params[:page].to_i > 0 ? params[:page].to_i : 0 
      else
        1
      end
    end

    def set_auction
      @auction = Auction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auction_params
      params.fetch(:auction, {})
    end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Auctions</h1>
<style>
.money-gold::after {
    content: "g";
    color: #DDB100;
}
.money-silver::after {
    content: "s";
    color: #bbb;
}

</style>

<%= bootstrap_form_for(Auction.new, url: auctions_path, method: :get, layout: :inline) do |f|%>
  <%= f.text_field :owner, hide_label: true, placeholder: 'Auction owner...', value: @last_search %>
  <%= f.submit 'Search', class: 'btn btn-primary' %>
<% end %>
<small> <%= @auctions.count %> results </small>

<%= paginate @auctions, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm"%>
<table class='table table-sm table-striped table-hover'>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Item</th>
      <th>quantity</th>
      <th>buyout</th>
      <th>time left</th>
      <th>updated ago
    </tr>
  </thead>

  <tbody>

    <% @auctions.each do |auction| %>
      <tr>

        <td><%= auction.owner %>
        <td>
          <%= link_to item_path(Item.where(item_id: auction.item).first.id) do %>
            <img src="https://wow.zamimg.com/images/wow/icons/small/<%=Item.where(item_id: auction.item).first.icon%>.jpg">
            <%= Item.where(item_id: auction.item).first.name %>
          <% end %>
        <td><%= auction.quantity %>
        <td>
          <span class='money-gold'><%= separated_price(auction.buyout)[:gold] %></span>, 
          <span class='money-silver'><%= separated_price(auction.buyout)[:silver] %></span>
        <td><%= auction.timeLeft %>
        <td><%=time_ago_in_words auction.updated_at%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auction', new_auction_path %>

app/views/auctions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_auction_path(@auction) %> |
<%= link_to 'Back', auctions_path %>