config/routes.rb
Rails.application.routes.draw do

  resources :recipes
  root to: 'items#index'


  resources :items, except: [:create, :delete, :update] do
    get 'item_auctions_data'
  end
  resources :auctions, except: [:create, :delete, :update]

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        
    </div>
    <div>
        implemented by <strong style='color: #F58CBA'>Selandir</strong> @ 2018
    </div>
</div>

app/views/layouts/_topnavbar_2.html.erb
<div class="row border-bottom white-bg">
    <nav class="navbar navbar-static-top" role="navigation">
        <div class="navbar-header">
            <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                <i class="fa fa-reorder"></i>
            </button>
            <a href="#" class="navbar-brand">AuctionWatcher</a>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
            <ul class="nav navbar-nav">
                <li>
                    <%= link_to 'Item list', items_path %>
                </li>
                <li>
                    <%= link_to 'Auction list', auctions_path %>
                </li>
                <li>
                    <%= link_to 'Recipe list', recipes_path %>
                </li>
            </ul>
            <ul class="nav navbar-top-links navbar-right">
                <li>

                        <em style='font-size: 10px; float: right;'>
                            <table>
                                <tr>
                                    <td style='padding: 3px;'>feed: 
                                    <td style='padding: 3px;'><%=time_ago_in_words Timestamp.order(:created_at).last.timestamp%> ago 
                                    <td style='padding: 3px;'>timestamp:
                                    <td style='padding: 3px;'><%= Timestamp.order(:created_at).last.id %>
                                <tr>
                                    <td style='padding: 3px;'>system:
                                    <td style='padding: 3px;'><%=time_ago_in_words Timestamp.order(:updated_at).last.updated_at%> ago
                                    <td style='padding: 3px;'>Jobs:
                                    <td style='padding: 3px;'><%= queue_size %>

                            </table>
                        </em>
                </li>
            </ul>
        </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auctionwatcher</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="top-navigation">

    <!-- Wrapper-->
    <div id="wrapper" class="<%= params[:controller] %>.<%= params[:action] %>">

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg <%= @extra_class %>">

            <!-- Page wrapper -->
            <%= render 'layouts/topnavbar_2' %>

            <!-- Main view  -->
            <%= yield %>

            <!-- Footer -->
            <%= render 'layouts/footer' %>

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->


    <!-- Include javascript per-view -->
    <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
    <%= yield :javascript %>

</body>

</html>